name: Deploy ke VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode (Opsional, karena VPS yang clone)
        uses: actions/checkout@v3

      - name: Setup SSH untuk ke VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -H 103.84.206.147 >> ~/.ssh/known_hosts

      - name: Jalankan deploy script di VPS
        run: ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes root@103.84.206.147 'bash /root/deploy.sh'
